package com.example.ffridge.ui.theme

import androidx.compose.ui.graphics.Color

// Frost Theme (Ice Blue)
val FrostPrimary = Color(0xFF2563EB)
val FrostPrimaryVariant = Color(0xFF1E40AF)
val FrostSecondary = Color(0xFF06B6D4)
val FrostSecondaryVariant = Color(0xFF0891B2)
val FrostTertiary = Color(0xFF8B5CF6)
val FrostBackground = Color(0xFFF0F9FF)
val FrostSurface = Color(0xFFFFFFFF)
val FrostSurfaceVariant = Color(0xFFE0F2FE)
val FrostOnPrimary = Color(0xFFFFFFFF)
val FrostOnSecondary = Color(0xFFFFFFFF)
val FrostOnBackground = Color(0xFF0F172A)
val FrostOnSurface = Color(0xFF0F172A)
val FrostOnSurfaceVariant = Color(0xFF475569)
val FrostError = Color(0xFFEF4444)
val FrostOnError = Color(0xFFFFFFFF)

// Midnight Theme (Dark Purple)
val MidnightPrimary = Color(0xFF6366F1)
val MidnightPrimaryVariant = Color(0xFF4F46E5)
val MidnightSecondary = Color(0xFF8B5CF6)
val MidnightSecondaryVariant = Color(0xFF7C3AED)
val MidnightTertiary = Color(0xFFA78BFA)
val MidnightBackground = Color(0xFF0F172A)
val MidnightSurface = Color(0xFF1E293B)
val MidnightSurfaceVariant = Color(0xFF334155)
val MidnightOnPrimary = Color(0xFFFFFFFF)
val MidnightOnSecondary = Color(0xFFFFFFFF)
val MidnightOnBackground = Color(0xFFF1F5F9)
val MidnightOnSurface = Color(0xFFF1F5F9)
val MidnightOnSurfaceVariant = Color(0xFFCBD5E1)
val MidnightError = Color(0xFFF87171)
val MidnightOnError = Color(0xFF1E293B)

// Sunrise Theme (Warm Orange)
val SunrisePrimary = Color(0xFFF97316)
val SunrisePrimaryVariant = Color(0xFFEA580C)
val SunriseSecondary = Color(0xFFF43F5E)
val SunriseSecondaryVariant = Color(0xFFE11D48)
val SunriseTertiary = Color(0xFFFB923C)
val SunriseBackground = Color(0xFFFFF7ED)
val SunriseSurface = Color(0xFFFFFFFF)
val SunriseSurfaceVariant = Color(0xFFFFEDD5)
val SunriseOnPrimary = Color(0xFFFFFFFF)
val SunriseOnSecondary = Color(0xFFFFFFFF)
val SunriseOnBackground = Color(0xFF292524)
val SunriseOnSurface = Color(0xFF292524)
val SunriseOnSurfaceVariant = Color(0xFF78716C)
val SunriseError = Color(0xFFDC2626)
val SunriseOnError = Color(0xFFFFFFFF)

// Additional UI Colors
val SuccessGreen = Color(0xFF10B981)
val WarningYellow = Color(0xFFF59E0B)
val InfoBlue = Color(0xFF3B82F6)

// Gradient Colors
val GradientStart = Color(0xFF667EEA)
val GradientEnd = Color(0xFF764BA2)
